<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'demo' => 'Demo'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* Auto generated by Modules Administration on : 2013.09.13 23:12:53 */
