<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'demo' => 'Demo',
	'login' => 'Login'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* Auto generated by Modules Administration on : 2013.09.21 01:00:30 */
